Dashboard frontend setup fatoumata
Irisvella/InventoryPilot pull request #62
Opened 2024-12-18 18:34 UTC by Fatoumatabintabarry

Fixing routes and fecthing data for admin and manager dashbaord and adding a avatar of the header

2024-12-18 18:53 UTC, flo351 approved these changes
Looks good !

2024-12-18 19:27 UTC, Irisvella requested changes

2024-12-18 19:27 UTC, Irisvella commented on WarehousePilot_app/frontend/src/App.jsx
can you add the route for KPI in the /component/routes pls. It will automatically import it here

2024-12-19 03:17 UTC, Irisvella approved these changes

2024-12-19 03:18 UTC, merged