sku-level-backend-1.0-issue #26
Irisvella/InventoryPilot pull request #67
Opened 2024-12-23 06:24 UTC by strikeyamato

Added utils.py for check_sku_alerts function which has a filter. Created a model, and updated the views.py and urls.py files. Ensured sku_color is the primary key based on recent db changes.

TO DO: Create automatic trigger for the alerts

2024-12-28 22:49 UTC, Irisvella commented
There are conflicts to resolve

2024-12-29 02:32 UTC, strikeyamato commented
Conflicts resolved. Awaiting review

2024-12-29 18:52 UTC, Irisvella requested changes

2024-12-29 18:52 UTC, Irisvella commented on WarehousePilot_app/backend/manager_dashboard/urls.py
remove profileview and changepassword view. They dont go there

2024-12-29 18:52 UTC, Irisvella commented on WarehousePilot_app/backend/manager_dashboard/views.py
same here, the APIs dont go here

2024-12-29 19:03 UTC, strikeyamato reviewed
removed profileview and changepassword from views.py and urls.py

2024-12-29 19:04 UTC, Irisvella approved these changes

2024-12-29 19:04 UTC, strikeyamato commented on WarehousePilot_app/backend/manager_dashboard/urls.py
Removed

2024-12-29 21:02 UTC, yousefenein commented
looks good, just need to integrate this with inventory

2024-12-29 21:03 UTC, yousefenein commented
looks good, just need to integrate this with inventory

2024-12-29 21:05 UTC, yousefenein approved these changes
looks good!

2024-12-29 21:05 UTC, merged